### PR TITLE
Upgrading version of torso to 0.6.9

### PR DESCRIPTION
**Pull request by mandragorn**

### CODE REVIEW

**Comment by kentmw** [comment]
Any problems when you do yo torso?

**Comment by mandragorn** [comment]
yes, fixing those now

**Comment by mandragorn** [comment]
after linking things correctly the only issue is that the handlebar helpers are not available, do we want to address that?

Otherwise this works out of the box with the update to just the torso dependency.

**Comment by kentmw** [comment]
Not available? Like handlebars dependency is missing

**Comment by mandragorn** [comment]
`Error: Missing helper: 'labelFor'` is in the console if you include {{labelFor 'blah'}} in an .hbs file.

**Pull request merged**
